# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - brew update
  - gem install cocoapods --pre
  - pod install
script:
  - xctool build-tests -workspace VoteApp.xcworkspace -scheme VoteApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool run-tests -workspace VoteApp.xcworkspace -scheme VoteApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 5s,OS=latest"

